name: Docker Image CI

on:
  push:
    paths:
    - 'gitpod/Dockerfile*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Build and push the Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/kondoumh/devel-containers/gitpod
        username: kondoumh
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
        registry: docker.pkg.github.com
        workdir: gitpod
        dockerfile: Dockerfile
